services:
    moomoo_menu.registrator.admin_menu_pages:
        class: 'MooMoo\Platform\Bundle\MenuBundle\Registrator\AdminMenuPagesRegistrator'
        public: true
        arguments:
            - '@moomoo_page.registry'

    moomoo_menu.registrator.admin_bar_nodes:
        class: 'MooMoo\Platform\Bundle\MenuBundle\Registrator\AdminBarNodesRegistrator'
        public: true

    moomoo_menu.registry.admin_menu_pages:
        class: 'MooMoo\Platform\Bundle\MenuBundle\Registry\MenuElementsRegistry'
        public: true

    moomoo_menu.registry.admin_bar_nodes:
        class: 'MooMoo\Platform\Bundle\MenuBundle\Registry\MenuElementsRegistry'
        public: true
