services:
    moomoo_taxonomy.registry.taxonomies:
        class: 'MooMoo\Platform\Bundle\TaxonomyBundle\Registry\TaxonomiesRegistry'
        public: true

    moomoo_taxonomy.registrator.taxonomies:
        class: 'MooMoo\Platform\Bundle\TaxonomyBundle\Registrator\TaxonomiesRegistrator'
        public: true
